#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 118
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 6

enum {
  anon_sym_COLON = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_DASH_GT = 6,
  sym_int = 7,
  sym_string = 8,
  sym_char = 9,
  anon_sym_COMMA = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_case = 13,
  anon_sym_DOT_DOT = 14,
  anon_sym_let = 15,
  anon_sym_EQ = 16,
  sym_l_ident = 17,
  sym_u_ident = 18,
  sym_source_file = 19,
  sym__decl = 20,
  sym_func_decl = 21,
  sym__type = 22,
  sym__atomic_type = 23,
  sym_type_name = 24,
  sym_var_type = 25,
  sym_app_type = 26,
  sym_func_type = 27,
  sym__expr = 28,
  sym__expr_except_var = 29,
  sym_ctor = 30,
  sym_tuple = 31,
  sym_list = 32,
  sym_case = 33,
  sym_branch = 34,
  sym__pattern = 35,
  sym__atomic_pattern = 36,
  sym_int_pattern = 37,
  sym_var_pattern = 38,
  sym_nullary_ctor_pattern = 39,
  sym_ctor_pattern = 40,
  sym_list_pattern = 41,
  sym_list_pattern_rest = 42,
  sym_tuple_pattern = 43,
  sym_func_or_app = 44,
  sym_func_params = 45,
  sym_let = 46,
  sym_let_bind = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_app_type_repeat1 = 49,
  aux_sym_tuple_repeat1 = 50,
  aux_sym_case_repeat1 = 51,
  aux_sym_ctor_pattern_repeat1 = 52,
  aux_sym_list_pattern_repeat1 = 53,
  aux_sym_func_params_repeat1 = 54,
  aux_sym_let_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [sym_int] = "int",
  [sym_string] = "string",
  [sym_char] = "char",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_case] = "case",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [sym_l_ident] = "l_ident",
  [sym_u_ident] = "u_ident",
  [sym_source_file] = "source_file",
  [sym__decl] = "_decl",
  [sym_func_decl] = "func_decl",
  [sym__type] = "_type",
  [sym__atomic_type] = "_atomic_type",
  [sym_type_name] = "type_name",
  [sym_var_type] = "var_type",
  [sym_app_type] = "app_type",
  [sym_func_type] = "func_type",
  [sym__expr] = "_expr",
  [sym__expr_except_var] = "_expr_except_var",
  [sym_ctor] = "ctor",
  [sym_tuple] = "tuple",
  [sym_list] = "list",
  [sym_case] = "case",
  [sym_branch] = "branch",
  [sym__pattern] = "_pattern",
  [sym__atomic_pattern] = "_atomic_pattern",
  [sym_int_pattern] = "int_pattern",
  [sym_var_pattern] = "var_pattern",
  [sym_nullary_ctor_pattern] = "nullary_ctor_pattern",
  [sym_ctor_pattern] = "ctor_pattern",
  [sym_list_pattern] = "list_pattern",
  [sym_list_pattern_rest] = "list_pattern_rest",
  [sym_tuple_pattern] = "tuple_pattern",
  [sym_func_or_app] = "func_or_app",
  [sym_func_params] = "func_params",
  [sym_let] = "let",
  [sym_let_bind] = "let_bind",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_app_type_repeat1] = "app_type_repeat1",
  [aux_sym_tuple_repeat1] = "tuple_repeat1",
  [aux_sym_case_repeat1] = "case_repeat1",
  [aux_sym_ctor_pattern_repeat1] = "ctor_pattern_repeat1",
  [aux_sym_list_pattern_repeat1] = "list_pattern_repeat1",
  [aux_sym_func_params_repeat1] = "func_params_repeat1",
  [aux_sym_let_repeat1] = "let_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_int] = sym_int,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_l_ident] = sym_l_ident,
  [sym_u_ident] = sym_u_ident,
  [sym_source_file] = sym_source_file,
  [sym__decl] = sym__decl,
  [sym_func_decl] = sym_func_decl,
  [sym__type] = sym__type,
  [sym__atomic_type] = sym__atomic_type,
  [sym_type_name] = sym_type_name,
  [sym_var_type] = sym_var_type,
  [sym_app_type] = sym_app_type,
  [sym_func_type] = sym_func_type,
  [sym__expr] = sym__expr,
  [sym__expr_except_var] = sym__expr_except_var,
  [sym_ctor] = sym_ctor,
  [sym_tuple] = sym_tuple,
  [sym_list] = sym_list,
  [sym_case] = sym_case,
  [sym_branch] = sym_branch,
  [sym__pattern] = sym__pattern,
  [sym__atomic_pattern] = sym__atomic_pattern,
  [sym_int_pattern] = sym_int_pattern,
  [sym_var_pattern] = sym_var_pattern,
  [sym_nullary_ctor_pattern] = sym_nullary_ctor_pattern,
  [sym_ctor_pattern] = sym_ctor_pattern,
  [sym_list_pattern] = sym_list_pattern,
  [sym_list_pattern_rest] = sym_list_pattern_rest,
  [sym_tuple_pattern] = sym_tuple_pattern,
  [sym_func_or_app] = sym_func_or_app,
  [sym_func_params] = sym_func_params,
  [sym_let] = sym_let,
  [sym_let_bind] = sym_let_bind,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_app_type_repeat1] = aux_sym_app_type_repeat1,
  [aux_sym_tuple_repeat1] = aux_sym_tuple_repeat1,
  [aux_sym_case_repeat1] = aux_sym_case_repeat1,
  [aux_sym_ctor_pattern_repeat1] = aux_sym_ctor_pattern_repeat1,
  [aux_sym_list_pattern_repeat1] = aux_sym_list_pattern_repeat1,
  [aux_sym_func_params_repeat1] = aux_sym_func_params_repeat1,
  [aux_sym_let_repeat1] = aux_sym_let_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_l_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_u_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__decl] = {
    .visible = false,
    .named = true,
  },
  [sym_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym__atomic_type] = {
    .visible = false,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_var_type] = {
    .visible = true,
    .named = true,
  },
  [sym_app_type] = {
    .visible = true,
    .named = true,
  },
  [sym_func_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__expr_except_var] = {
    .visible = false,
    .named = true,
  },
  [sym_ctor] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_case] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym__atomic_pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_int_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_var_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_nullary_ctor_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_ctor_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_list_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_list_pattern_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_func_or_app] = {
    .visible = true,
    .named = true,
  },
  [sym_func_params] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_let_bind] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_app_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_case_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ctor_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_let_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_head = 2,
  field_name = 3,
  field_pattern = 4,
  field_rhs = 5,
  field_type = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_head] = "head",
  [field_name] = "name",
  [field_pattern] = "pattern",
  [field_rhs] = "rhs",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_head, 0},
  [1] =
    {field_body, 4},
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_body, 2},
  [5] =
    {field_body, 3},
  [6] =
    {field_pattern, 0},
    {field_rhs, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 50,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 64,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == 'c') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(1);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(4);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_case);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'a') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 's') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 't') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_l_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_u_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 9},
  [69] = {.lex_state = 9},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 9},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 9},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 9},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 9},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 9},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_l_ident] = ACTIONS(1),
    [sym_u_ident] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(116),
    [sym__decl] = STATE(72),
    [sym_func_decl] = STATE(72),
    [aux_sym_source_file_repeat1] = STATE(72),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_l_ident] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      anon_sym_COMMA,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(11), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(78), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [46] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(25), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [89] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(25), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [132] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(25), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [175] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(25), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [218] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(35), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(79), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [261] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_u_ident,
    ACTIONS(41), 1,
      sym_l_ident,
    STATE(73), 1,
      aux_sym_func_params_repeat1,
    STATE(81), 1,
      sym_func_params,
    ACTIONS(39), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(98), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [301] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(25), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [341] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(43), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(110), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [381] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_u_ident,
    ACTIONS(41), 1,
      sym_l_ident,
    STATE(73), 1,
      aux_sym_func_params_repeat1,
    STATE(81), 1,
      sym_func_params,
    ACTIONS(45), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(61), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [421] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(47), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(105), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [461] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(49), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(96), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [501] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(51), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(111), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [541] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_case,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      sym_l_ident,
    ACTIONS(23), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(45), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(61), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [581] = 10,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(57), 1,
      anon_sym_COMMA,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_RBRACK,
    ACTIONS(63), 1,
      anon_sym_DOT_DOT,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    STATE(114), 1,
      sym_list_pattern_rest,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [619] = 10,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_DOT_DOT,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(69), 1,
      anon_sym_COMMA,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    STATE(109), 1,
      sym_list_pattern_rest,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [657] = 10,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_DOT_DOT,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
    STATE(115), 1,
      sym_list_pattern_rest,
    STATE(84), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [695] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(79), 1,
      sym_u_ident,
    ACTIONS(77), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(20), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [726] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(79), 1,
      sym_u_ident,
    ACTIONS(81), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [757] = 7,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      sym_int,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      sym_l_ident,
    ACTIONS(97), 1,
      sym_u_ident,
    ACTIONS(86), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [788] = 8,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [820] = 8,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [852] = 8,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [884] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(106), 1,
      anon_sym_RPAREN,
    STATE(87), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [913] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(108), 1,
      anon_sym_RPAREN,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [942] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    STATE(95), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [971] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1000] = 6,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_l_ident,
    ACTIONS(67), 1,
      sym_u_ident,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1026] = 5,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym_l_ident,
    ACTIONS(120), 1,
      sym_u_ident,
    ACTIONS(112), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(30), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1047] = 5,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      sym_l_ident,
    ACTIONS(129), 1,
      sym_u_ident,
    ACTIONS(123), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(32), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1068] = 5,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      sym_l_ident,
    ACTIONS(129), 1,
      sym_u_ident,
    ACTIONS(131), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(30), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1089] = 2,
    ACTIONS(135), 1,
      sym_u_ident,
    ACTIONS(133), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1103] = 2,
    ACTIONS(139), 1,
      sym_u_ident,
    ACTIONS(137), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1117] = 2,
    ACTIONS(143), 1,
      sym_u_ident,
    ACTIONS(141), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1131] = 5,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      sym_l_ident,
    ACTIONS(129), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(99), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1151] = 2,
    ACTIONS(147), 1,
      sym_u_ident,
    ACTIONS(145), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1165] = 5,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      sym_l_ident,
    ACTIONS(129), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(100), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1185] = 2,
    ACTIONS(149), 1,
      sym_u_ident,
    ACTIONS(77), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1199] = 2,
    ACTIONS(153), 1,
      sym_u_ident,
    ACTIONS(151), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1213] = 2,
    ACTIONS(157), 1,
      sym_u_ident,
    ACTIONS(155), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1227] = 2,
    ACTIONS(161), 1,
      sym_u_ident,
    ACTIONS(159), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1241] = 2,
    ACTIONS(165), 1,
      sym_u_ident,
    ACTIONS(163), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1255] = 2,
    ACTIONS(169), 1,
      sym_u_ident,
    ACTIONS(167), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1269] = 2,
    ACTIONS(173), 1,
      sym_u_ident,
    ACTIONS(171), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1283] = 2,
    ACTIONS(177), 1,
      sym_u_ident,
    ACTIONS(175), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1297] = 2,
    ACTIONS(181), 1,
      sym_u_ident,
    ACTIONS(179), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1311] = 5,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      sym_l_ident,
    ACTIONS(129), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(86), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1331] = 3,
    ACTIONS(185), 1,
      sym_l_ident,
    STATE(49), 1,
      aux_sym_func_params_repeat1,
    ACTIONS(183), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1346] = 3,
    ACTIONS(190), 1,
      sym_l_ident,
    STATE(49), 1,
      aux_sym_func_params_repeat1,
    ACTIONS(188), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1361] = 1,
    ACTIONS(192), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1370] = 1,
    ACTIONS(194), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1379] = 1,
    ACTIONS(196), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1388] = 1,
    ACTIONS(198), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1397] = 1,
    ACTIONS(200), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1406] = 1,
    ACTIONS(202), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1415] = 2,
    ACTIONS(206), 1,
      sym_u_ident,
    ACTIONS(204), 5,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1426] = 1,
    ACTIONS(208), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1435] = 1,
    ACTIONS(210), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1444] = 1,
    ACTIONS(212), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1453] = 1,
    ACTIONS(214), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1462] = 1,
    ACTIONS(216), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1471] = 1,
    ACTIONS(218), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1480] = 2,
    ACTIONS(222), 1,
      anon_sym_DASH_GT,
    ACTIONS(220), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1491] = 1,
    ACTIONS(224), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1500] = 1,
    ACTIONS(226), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1509] = 1,
    ACTIONS(228), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1518] = 2,
    ACTIONS(232), 1,
      sym_u_ident,
    ACTIONS(230), 5,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1529] = 1,
    ACTIONS(234), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1538] = 2,
    ACTIONS(238), 1,
      sym_u_ident,
    ACTIONS(236), 5,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1549] = 3,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
    ACTIONS(242), 1,
      sym_l_ident,
    STATE(71), 3,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [1561] = 3,
    ACTIONS(5), 1,
      sym_l_ident,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    STATE(71), 3,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [1573] = 2,
    STATE(49), 1,
      aux_sym_func_params_repeat1,
    ACTIONS(188), 3,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1582] = 3,
    ACTIONS(247), 1,
      anon_sym_LBRACE,
    ACTIONS(249), 1,
      sym_l_ident,
    STATE(74), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1593] = 3,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
    ACTIONS(254), 1,
      sym_l_ident,
    STATE(74), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1604] = 3,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
    ACTIONS(256), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1615] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_pattern_repeat1,
    ACTIONS(261), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1626] = 3,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_tuple_repeat1,
  [1636] = 3,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RBRACK,
    STATE(89), 1,
      aux_sym_tuple_repeat1,
  [1646] = 3,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_case_repeat1,
  [1656] = 2,
    ACTIONS(276), 1,
      anon_sym_DASH_GT,
    ACTIONS(220), 2,
      anon_sym_LBRACE,
      sym_l_ident,
  [1664] = 3,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_case_repeat1,
  [1674] = 2,
    ACTIONS(254), 1,
      sym_l_ident,
    STATE(75), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1682] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      aux_sym_list_pattern_repeat1,
  [1692] = 3,
    ACTIONS(108), 1,
      anon_sym_RPAREN,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_pattern_repeat1,
  [1702] = 2,
    ACTIONS(290), 1,
      anon_sym_DASH_GT,
    ACTIONS(288), 2,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
  [1710] = 3,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_list_pattern_repeat1,
  [1720] = 3,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
  [1730] = 3,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
  [1740] = 3,
    ACTIONS(61), 1,
      anon_sym_RBRACK,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_pattern_repeat1,
  [1750] = 1,
    ACTIONS(261), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1756] = 1,
    ACTIONS(256), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1762] = 3,
    ACTIONS(302), 1,
      anon_sym_RBRACE,
    ACTIONS(304), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_case_repeat1,
  [1772] = 2,
    ACTIONS(63), 1,
      anon_sym_DOT_DOT,
    STATE(113), 1,
      sym_list_pattern_rest,
  [1779] = 1,
    ACTIONS(302), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1784] = 1,
    ACTIONS(307), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1789] = 2,
    ACTIONS(63), 1,
      anon_sym_DOT_DOT,
    STATE(108), 1,
      sym_list_pattern_rest,
  [1796] = 1,
    ACTIONS(309), 2,
      anon_sym_LBRACE,
      sym_l_ident,
  [1801] = 2,
    ACTIONS(290), 1,
      anon_sym_DASH_GT,
    ACTIONS(311), 1,
      anon_sym_LBRACE,
  [1808] = 2,
    ACTIONS(290), 1,
      anon_sym_DASH_GT,
    ACTIONS(313), 1,
      anon_sym_RPAREN,
  [1815] = 1,
    ACTIONS(315), 2,
      ts_builtin_sym_end,
      sym_l_ident,
  [1820] = 2,
    ACTIONS(63), 1,
      anon_sym_DOT_DOT,
    STATE(109), 1,
      sym_list_pattern_rest,
  [1827] = 1,
    ACTIONS(317), 1,
      anon_sym_RBRACK,
  [1831] = 1,
    ACTIONS(319), 1,
      anon_sym_EQ,
  [1835] = 1,
    ACTIONS(321), 1,
      anon_sym_LBRACE,
  [1839] = 1,
    ACTIONS(323), 1,
      anon_sym_COLON,
  [1843] = 1,
    ACTIONS(325), 1,
      anon_sym_RPAREN,
  [1847] = 1,
    ACTIONS(61), 1,
      anon_sym_RBRACK,
  [1851] = 1,
    ACTIONS(327), 1,
      anon_sym_RBRACK,
  [1855] = 1,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
  [1859] = 1,
    ACTIONS(331), 1,
      anon_sym_RBRACE,
  [1863] = 1,
    ACTIONS(333), 1,
      sym_l_ident,
  [1867] = 1,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
  [1871] = 1,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
  [1875] = 1,
    ACTIONS(284), 1,
      anon_sym_RBRACK,
  [1879] = 1,
    ACTIONS(337), 1,
      ts_builtin_sym_end,
  [1883] = 1,
    ACTIONS(339), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 89,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 175,
  [SMALL_STATE(7)] = 218,
  [SMALL_STATE(8)] = 261,
  [SMALL_STATE(9)] = 301,
  [SMALL_STATE(10)] = 341,
  [SMALL_STATE(11)] = 381,
  [SMALL_STATE(12)] = 421,
  [SMALL_STATE(13)] = 461,
  [SMALL_STATE(14)] = 501,
  [SMALL_STATE(15)] = 541,
  [SMALL_STATE(16)] = 581,
  [SMALL_STATE(17)] = 619,
  [SMALL_STATE(18)] = 657,
  [SMALL_STATE(19)] = 695,
  [SMALL_STATE(20)] = 726,
  [SMALL_STATE(21)] = 757,
  [SMALL_STATE(22)] = 788,
  [SMALL_STATE(23)] = 820,
  [SMALL_STATE(24)] = 852,
  [SMALL_STATE(25)] = 884,
  [SMALL_STATE(26)] = 913,
  [SMALL_STATE(27)] = 942,
  [SMALL_STATE(28)] = 971,
  [SMALL_STATE(29)] = 1000,
  [SMALL_STATE(30)] = 1026,
  [SMALL_STATE(31)] = 1047,
  [SMALL_STATE(32)] = 1068,
  [SMALL_STATE(33)] = 1089,
  [SMALL_STATE(34)] = 1103,
  [SMALL_STATE(35)] = 1117,
  [SMALL_STATE(36)] = 1131,
  [SMALL_STATE(37)] = 1151,
  [SMALL_STATE(38)] = 1165,
  [SMALL_STATE(39)] = 1185,
  [SMALL_STATE(40)] = 1199,
  [SMALL_STATE(41)] = 1213,
  [SMALL_STATE(42)] = 1227,
  [SMALL_STATE(43)] = 1241,
  [SMALL_STATE(44)] = 1255,
  [SMALL_STATE(45)] = 1269,
  [SMALL_STATE(46)] = 1283,
  [SMALL_STATE(47)] = 1297,
  [SMALL_STATE(48)] = 1311,
  [SMALL_STATE(49)] = 1331,
  [SMALL_STATE(50)] = 1346,
  [SMALL_STATE(51)] = 1361,
  [SMALL_STATE(52)] = 1370,
  [SMALL_STATE(53)] = 1379,
  [SMALL_STATE(54)] = 1388,
  [SMALL_STATE(55)] = 1397,
  [SMALL_STATE(56)] = 1406,
  [SMALL_STATE(57)] = 1415,
  [SMALL_STATE(58)] = 1426,
  [SMALL_STATE(59)] = 1435,
  [SMALL_STATE(60)] = 1444,
  [SMALL_STATE(61)] = 1453,
  [SMALL_STATE(62)] = 1462,
  [SMALL_STATE(63)] = 1471,
  [SMALL_STATE(64)] = 1480,
  [SMALL_STATE(65)] = 1491,
  [SMALL_STATE(66)] = 1500,
  [SMALL_STATE(67)] = 1509,
  [SMALL_STATE(68)] = 1518,
  [SMALL_STATE(69)] = 1529,
  [SMALL_STATE(70)] = 1538,
  [SMALL_STATE(71)] = 1549,
  [SMALL_STATE(72)] = 1561,
  [SMALL_STATE(73)] = 1573,
  [SMALL_STATE(74)] = 1582,
  [SMALL_STATE(75)] = 1593,
  [SMALL_STATE(76)] = 1604,
  [SMALL_STATE(77)] = 1615,
  [SMALL_STATE(78)] = 1626,
  [SMALL_STATE(79)] = 1636,
  [SMALL_STATE(80)] = 1646,
  [SMALL_STATE(81)] = 1656,
  [SMALL_STATE(82)] = 1664,
  [SMALL_STATE(83)] = 1674,
  [SMALL_STATE(84)] = 1682,
  [SMALL_STATE(85)] = 1692,
  [SMALL_STATE(86)] = 1702,
  [SMALL_STATE(87)] = 1710,
  [SMALL_STATE(88)] = 1720,
  [SMALL_STATE(89)] = 1730,
  [SMALL_STATE(90)] = 1740,
  [SMALL_STATE(91)] = 1750,
  [SMALL_STATE(92)] = 1756,
  [SMALL_STATE(93)] = 1762,
  [SMALL_STATE(94)] = 1772,
  [SMALL_STATE(95)] = 1779,
  [SMALL_STATE(96)] = 1784,
  [SMALL_STATE(97)] = 1789,
  [SMALL_STATE(98)] = 1796,
  [SMALL_STATE(99)] = 1801,
  [SMALL_STATE(100)] = 1808,
  [SMALL_STATE(101)] = 1815,
  [SMALL_STATE(102)] = 1820,
  [SMALL_STATE(103)] = 1827,
  [SMALL_STATE(104)] = 1831,
  [SMALL_STATE(105)] = 1835,
  [SMALL_STATE(106)] = 1839,
  [SMALL_STATE(107)] = 1843,
  [SMALL_STATE(108)] = 1847,
  [SMALL_STATE(109)] = 1851,
  [SMALL_STATE(110)] = 1855,
  [SMALL_STATE(111)] = 1859,
  [SMALL_STATE(112)] = 1863,
  [SMALL_STATE(113)] = 1867,
  [SMALL_STATE(114)] = 1871,
  [SMALL_STATE(115)] = 1875,
  [SMALL_STATE(116)] = 1879,
  [SMALL_STATE(117)] = 1883,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nullary_ctor_pattern, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctor_pattern, 2),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(25),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(33),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(18),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(47),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(39),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(38),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(70),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(68),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_app_type, 2, .production_id = 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_pattern, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_pattern, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 5),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 5),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nullary_ctor_pattern, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 7),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 7),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 4),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 4),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 4),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 5),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 5),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 6),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 6),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_pattern, 1),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_pattern, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_params_repeat1, 2),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_params_repeat1, 2), SHIFT_REPEAT(49),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_params, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctor, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 4),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atomic_type, 3),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atomic_type, 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 6),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_except_var, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_or_app, 3, .production_id = 3),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 5, .production_id = 4),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_or_app, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 7),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_name, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 5),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_type, 1),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_type, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(106),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2), SHIFT_REPEAT(104),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2), SHIFT_REPEAT(9),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_pattern_repeat1, 2),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_pattern_repeat1, 2), SHIFT_REPEAT(29),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_type, 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_case_repeat1, 2),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_case_repeat1, 2), SHIFT_REPEAT(27),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 3, .production_id = 5),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_bind, 3),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 6, .production_id = 2),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern_rest, 2),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [337] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
