#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 118
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 6

enum {
  sym_comment = 1,
  anon_sym_COLON = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_DASH_GT = 7,
  sym_int = 8,
  sym_string = 9,
  sym_char = 10,
  anon_sym_COMMA = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  anon_sym_case = 14,
  anon_sym_DOT_DOT = 15,
  anon_sym_let = 16,
  anon_sym_EQ = 17,
  sym_l_ident = 18,
  sym_u_ident = 19,
  sym_source_file = 20,
  sym__decl = 21,
  sym_func_decl = 22,
  sym__type = 23,
  sym__atomic_type = 24,
  sym_type_name = 25,
  sym_var_type = 26,
  sym_app_type = 27,
  sym_func_type = 28,
  sym__expr = 29,
  sym__expr_except_var = 30,
  sym_ctor = 31,
  sym_tuple = 32,
  sym_list = 33,
  sym_case = 34,
  sym_branch = 35,
  sym__pattern = 36,
  sym__atomic_pattern = 37,
  sym_int_pattern = 38,
  sym_var_pattern = 39,
  sym_nullary_ctor_pattern = 40,
  sym_ctor_pattern = 41,
  sym_list_pattern = 42,
  sym_list_pattern_rest = 43,
  sym_tuple_pattern = 44,
  sym_func_or_app = 45,
  sym_func_params = 46,
  sym_let = 47,
  sym_let_bind = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_app_type_repeat1 = 50,
  aux_sym_tuple_repeat1 = 51,
  aux_sym_case_repeat1 = 52,
  aux_sym_ctor_pattern_repeat1 = 53,
  aux_sym_list_pattern_repeat1 = 54,
  aux_sym_func_params_repeat1 = 55,
  aux_sym_let_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [sym_int] = "int",
  [sym_string] = "string",
  [sym_char] = "char",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_case] = "case",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [sym_l_ident] = "l_ident",
  [sym_u_ident] = "u_ident",
  [sym_source_file] = "source_file",
  [sym__decl] = "_decl",
  [sym_func_decl] = "func_decl",
  [sym__type] = "_type",
  [sym__atomic_type] = "_atomic_type",
  [sym_type_name] = "type_name",
  [sym_var_type] = "var_type",
  [sym_app_type] = "app_type",
  [sym_func_type] = "func_type",
  [sym__expr] = "_expr",
  [sym__expr_except_var] = "_expr_except_var",
  [sym_ctor] = "ctor",
  [sym_tuple] = "tuple",
  [sym_list] = "list",
  [sym_case] = "case",
  [sym_branch] = "branch",
  [sym__pattern] = "_pattern",
  [sym__atomic_pattern] = "_atomic_pattern",
  [sym_int_pattern] = "int_pattern",
  [sym_var_pattern] = "var_pattern",
  [sym_nullary_ctor_pattern] = "nullary_ctor_pattern",
  [sym_ctor_pattern] = "ctor_pattern",
  [sym_list_pattern] = "list_pattern",
  [sym_list_pattern_rest] = "list_pattern_rest",
  [sym_tuple_pattern] = "tuple_pattern",
  [sym_func_or_app] = "func_or_app",
  [sym_func_params] = "func_params",
  [sym_let] = "let",
  [sym_let_bind] = "let_bind",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_app_type_repeat1] = "app_type_repeat1",
  [aux_sym_tuple_repeat1] = "tuple_repeat1",
  [aux_sym_case_repeat1] = "case_repeat1",
  [aux_sym_ctor_pattern_repeat1] = "ctor_pattern_repeat1",
  [aux_sym_list_pattern_repeat1] = "list_pattern_repeat1",
  [aux_sym_func_params_repeat1] = "func_params_repeat1",
  [aux_sym_let_repeat1] = "let_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_int] = sym_int,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_l_ident] = sym_l_ident,
  [sym_u_ident] = sym_u_ident,
  [sym_source_file] = sym_source_file,
  [sym__decl] = sym__decl,
  [sym_func_decl] = sym_func_decl,
  [sym__type] = sym__type,
  [sym__atomic_type] = sym__atomic_type,
  [sym_type_name] = sym_type_name,
  [sym_var_type] = sym_var_type,
  [sym_app_type] = sym_app_type,
  [sym_func_type] = sym_func_type,
  [sym__expr] = sym__expr,
  [sym__expr_except_var] = sym__expr_except_var,
  [sym_ctor] = sym_ctor,
  [sym_tuple] = sym_tuple,
  [sym_list] = sym_list,
  [sym_case] = sym_case,
  [sym_branch] = sym_branch,
  [sym__pattern] = sym__pattern,
  [sym__atomic_pattern] = sym__atomic_pattern,
  [sym_int_pattern] = sym_int_pattern,
  [sym_var_pattern] = sym_var_pattern,
  [sym_nullary_ctor_pattern] = sym_nullary_ctor_pattern,
  [sym_ctor_pattern] = sym_ctor_pattern,
  [sym_list_pattern] = sym_list_pattern,
  [sym_list_pattern_rest] = sym_list_pattern_rest,
  [sym_tuple_pattern] = sym_tuple_pattern,
  [sym_func_or_app] = sym_func_or_app,
  [sym_func_params] = sym_func_params,
  [sym_let] = sym_let,
  [sym_let_bind] = sym_let_bind,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_app_type_repeat1] = aux_sym_app_type_repeat1,
  [aux_sym_tuple_repeat1] = aux_sym_tuple_repeat1,
  [aux_sym_case_repeat1] = aux_sym_case_repeat1,
  [aux_sym_ctor_pattern_repeat1] = aux_sym_ctor_pattern_repeat1,
  [aux_sym_list_pattern_repeat1] = aux_sym_list_pattern_repeat1,
  [aux_sym_func_params_repeat1] = aux_sym_func_params_repeat1,
  [aux_sym_let_repeat1] = aux_sym_let_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_l_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_u_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__decl] = {
    .visible = false,
    .named = true,
  },
  [sym_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym__atomic_type] = {
    .visible = false,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_var_type] = {
    .visible = true,
    .named = true,
  },
  [sym_app_type] = {
    .visible = true,
    .named = true,
  },
  [sym_func_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__expr_except_var] = {
    .visible = false,
    .named = true,
  },
  [sym_ctor] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_case] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym__atomic_pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_int_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_var_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_nullary_ctor_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_ctor_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_list_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_list_pattern_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_func_or_app] = {
    .visible = true,
    .named = true,
  },
  [sym_func_params] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_let_bind] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_app_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_case_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ctor_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_let_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_head = 2,
  field_name = 3,
  field_pattern = 4,
  field_rhs = 5,
  field_type = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_head] = "head",
  [field_name] = "name",
  [field_pattern] = "pattern",
  [field_rhs] = "rhs",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_head, 0},
  [1] =
    {field_body, 4},
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_body, 2},
  [5] =
    {field_body, 3},
  [6] =
    {field_pattern, 0},
    {field_rhs, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 50,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 64,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(10);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == 'c') ADVANCE(30);
      if (lookahead == 'l') ADVANCE(31);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(1);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(4);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(36);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_case);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'a') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'e') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 's') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 't') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_l_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_u_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 11},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 11},
  [42] = {.lex_state = 11},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 11},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 11},
  [62] = {.lex_state = 11},
  [63] = {.lex_state = 11},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 11},
  [66] = {.lex_state = 11},
  [67] = {.lex_state = 11},
  [68] = {.lex_state = 11},
  [69] = {.lex_state = 11},
  [70] = {.lex_state = 11},
  [71] = {.lex_state = 11},
  [72] = {.lex_state = 11},
  [73] = {.lex_state = 11},
  [74] = {.lex_state = 11},
  [75] = {.lex_state = 11},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 11},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 11},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 11},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 11},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 11},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_l_ident] = ACTIONS(1),
    [sym_u_ident] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(116),
    [sym__decl] = STATE(72),
    [sym_func_decl] = STATE(72),
    [aux_sym_source_file_repeat1] = STATE(72),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_l_ident] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(13), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(78), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [49] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(27), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [95] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(27), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [141] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(27), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [187] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(27), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [233] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(37), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(79), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [279] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_u_ident,
    ACTIONS(43), 1,
      sym_l_ident,
    STATE(73), 1,
      aux_sym_func_params_repeat1,
    STATE(81), 1,
      sym_func_params,
    ACTIONS(41), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(98), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [322] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(27), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(92), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [365] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(45), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(110), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [408] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_u_ident,
    ACTIONS(43), 1,
      sym_l_ident,
    STATE(73), 1,
      aux_sym_func_params_repeat1,
    STATE(81), 1,
      sym_func_params,
    ACTIONS(47), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(61), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [451] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(49), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(105), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [494] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(51), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(96), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [537] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(53), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(111), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [580] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_case,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_l_ident,
    ACTIONS(25), 1,
      sym_u_ident,
    STATE(50), 1,
      aux_sym_func_params_repeat1,
    STATE(64), 1,
      sym_func_params,
    ACTIONS(47), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(61), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [623] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(59), 1,
      anon_sym_COMMA,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    ACTIONS(65), 1,
      anon_sym_DOT_DOT,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    STATE(114), 1,
      sym_list_pattern_rest,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [664] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      anon_sym_DOT_DOT,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(71), 1,
      anon_sym_COMMA,
    ACTIONS(73), 1,
      anon_sym_RBRACK,
    STATE(109), 1,
      sym_list_pattern_rest,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [705] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      anon_sym_DOT_DOT,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(77), 1,
      anon_sym_RBRACK,
    STATE(115), 1,
      sym_list_pattern_rest,
    STATE(84), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [746] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(81), 1,
      sym_u_ident,
    ACTIONS(79), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(20), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [780] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(81), 1,
      sym_u_ident,
    ACTIONS(83), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [814] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_int,
    ACTIONS(93), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      sym_l_ident,
    ACTIONS(99), 1,
      sym_u_ident,
    ACTIONS(88), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [848] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [883] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [918] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [953] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(108), 1,
      anon_sym_RPAREN,
    STATE(87), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [985] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1017] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    STATE(95), 1,
      sym_branch,
    STATE(117), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1049] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1081] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      sym_l_ident,
    ACTIONS(69), 1,
      sym_u_ident,
    STATE(91), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1110] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      sym_l_ident,
    ACTIONS(122), 1,
      sym_u_ident,
    ACTIONS(114), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(30), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1134] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      sym_l_ident,
    ACTIONS(131), 1,
      sym_u_ident,
    ACTIONS(125), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(32), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1158] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      sym_l_ident,
    ACTIONS(131), 1,
      sym_u_ident,
    ACTIONS(133), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(30), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_u_ident,
    ACTIONS(135), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1199] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_u_ident,
    ACTIONS(139), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1216] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_u_ident,
    ACTIONS(143), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1233] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      sym_l_ident,
    ACTIONS(131), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(99), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1256] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_u_ident,
    ACTIONS(147), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1273] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      sym_l_ident,
    ACTIONS(131), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(100), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1296] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_u_ident,
    ACTIONS(79), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1313] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_u_ident,
    ACTIONS(153), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_u_ident,
    ACTIONS(157), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_u_ident,
    ACTIONS(161), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_u_ident,
    ACTIONS(165), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1381] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_u_ident,
    ACTIONS(169), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1398] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_u_ident,
    ACTIONS(173), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      sym_u_ident,
    ACTIONS(177), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1432] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_u_ident,
    ACTIONS(181), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_int,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1449] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      sym_l_ident,
    ACTIONS(131), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(86), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1472] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_l_ident,
    STATE(49), 1,
      aux_sym_func_params_repeat1,
    ACTIONS(185), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1490] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_l_ident,
    STATE(49), 1,
      aux_sym_func_params_repeat1,
    ACTIONS(190), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1508] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1580] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_u_ident,
    ACTIONS(206), 5,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1594] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1630] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1666] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_DASH_GT,
    ACTIONS(222), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1680] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1716] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_u_ident,
    ACTIONS(232), 5,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1742] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_u_ident,
    ACTIONS(238), 5,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1756] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 1,
      sym_l_ident,
    STATE(71), 3,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [1771] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_l_ident,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
    STATE(71), 3,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [1786] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      aux_sym_func_params_repeat1,
    ACTIONS(190), 3,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1798] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      sym_l_ident,
    STATE(74), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1812] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    ACTIONS(256), 1,
      sym_l_ident,
    STATE(74), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1826] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
    ACTIONS(258), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1840] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_pattern_repeat1,
    ACTIONS(263), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1854] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_tuple_repeat1,
  [1867] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RBRACK,
    STATE(89), 1,
      aux_sym_tuple_repeat1,
  [1880] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_case_repeat1,
  [1893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_DASH_GT,
    ACTIONS(222), 2,
      anon_sym_LBRACE,
      sym_l_ident,
  [1904] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_case_repeat1,
  [1917] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_l_ident,
    STATE(75), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1928] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      aux_sym_list_pattern_repeat1,
  [1941] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_pattern_repeat1,
  [1954] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_DASH_GT,
    ACTIONS(290), 2,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
  [1965] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_list_pattern_repeat1,
  [1978] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
  [1991] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
  [2004] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    ACTIONS(302), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_pattern_repeat1,
  [2017] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2035] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_RBRACE,
    ACTIONS(306), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      aux_sym_case_repeat1,
  [2048] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DOT_DOT,
    STATE(113), 1,
      sym_list_pattern_rest,
  [2058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2066] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2074] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DOT_DOT,
    STATE(108), 1,
      sym_list_pattern_rest,
  [2084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      anon_sym_LBRACE,
      sym_l_ident,
  [2092] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_DASH_GT,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
  [2102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_DASH_GT,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
  [2112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 2,
      ts_builtin_sym_end,
      sym_l_ident,
  [2120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DOT_DOT,
    STATE(109), 1,
      sym_list_pattern_rest,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_RBRACK,
  [2137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_EQ,
  [2144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_LBRACE,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COLON,
  [2158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
  [2165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_RBRACK,
  [2179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_RBRACE,
  [2186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_RBRACE,
  [2193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      sym_l_ident,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_RBRACK,
  [2207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_RBRACK,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
  [2221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      ts_builtin_sym_end,
  [2228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 95,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 187,
  [SMALL_STATE(7)] = 233,
  [SMALL_STATE(8)] = 279,
  [SMALL_STATE(9)] = 322,
  [SMALL_STATE(10)] = 365,
  [SMALL_STATE(11)] = 408,
  [SMALL_STATE(12)] = 451,
  [SMALL_STATE(13)] = 494,
  [SMALL_STATE(14)] = 537,
  [SMALL_STATE(15)] = 580,
  [SMALL_STATE(16)] = 623,
  [SMALL_STATE(17)] = 664,
  [SMALL_STATE(18)] = 705,
  [SMALL_STATE(19)] = 746,
  [SMALL_STATE(20)] = 780,
  [SMALL_STATE(21)] = 814,
  [SMALL_STATE(22)] = 848,
  [SMALL_STATE(23)] = 883,
  [SMALL_STATE(24)] = 918,
  [SMALL_STATE(25)] = 953,
  [SMALL_STATE(26)] = 985,
  [SMALL_STATE(27)] = 1017,
  [SMALL_STATE(28)] = 1049,
  [SMALL_STATE(29)] = 1081,
  [SMALL_STATE(30)] = 1110,
  [SMALL_STATE(31)] = 1134,
  [SMALL_STATE(32)] = 1158,
  [SMALL_STATE(33)] = 1182,
  [SMALL_STATE(34)] = 1199,
  [SMALL_STATE(35)] = 1216,
  [SMALL_STATE(36)] = 1233,
  [SMALL_STATE(37)] = 1256,
  [SMALL_STATE(38)] = 1273,
  [SMALL_STATE(39)] = 1296,
  [SMALL_STATE(40)] = 1313,
  [SMALL_STATE(41)] = 1330,
  [SMALL_STATE(42)] = 1347,
  [SMALL_STATE(43)] = 1364,
  [SMALL_STATE(44)] = 1381,
  [SMALL_STATE(45)] = 1398,
  [SMALL_STATE(46)] = 1415,
  [SMALL_STATE(47)] = 1432,
  [SMALL_STATE(48)] = 1449,
  [SMALL_STATE(49)] = 1472,
  [SMALL_STATE(50)] = 1490,
  [SMALL_STATE(51)] = 1508,
  [SMALL_STATE(52)] = 1520,
  [SMALL_STATE(53)] = 1532,
  [SMALL_STATE(54)] = 1544,
  [SMALL_STATE(55)] = 1556,
  [SMALL_STATE(56)] = 1568,
  [SMALL_STATE(57)] = 1580,
  [SMALL_STATE(58)] = 1594,
  [SMALL_STATE(59)] = 1606,
  [SMALL_STATE(60)] = 1618,
  [SMALL_STATE(61)] = 1630,
  [SMALL_STATE(62)] = 1642,
  [SMALL_STATE(63)] = 1654,
  [SMALL_STATE(64)] = 1666,
  [SMALL_STATE(65)] = 1680,
  [SMALL_STATE(66)] = 1692,
  [SMALL_STATE(67)] = 1704,
  [SMALL_STATE(68)] = 1716,
  [SMALL_STATE(69)] = 1730,
  [SMALL_STATE(70)] = 1742,
  [SMALL_STATE(71)] = 1756,
  [SMALL_STATE(72)] = 1771,
  [SMALL_STATE(73)] = 1786,
  [SMALL_STATE(74)] = 1798,
  [SMALL_STATE(75)] = 1812,
  [SMALL_STATE(76)] = 1826,
  [SMALL_STATE(77)] = 1840,
  [SMALL_STATE(78)] = 1854,
  [SMALL_STATE(79)] = 1867,
  [SMALL_STATE(80)] = 1880,
  [SMALL_STATE(81)] = 1893,
  [SMALL_STATE(82)] = 1904,
  [SMALL_STATE(83)] = 1917,
  [SMALL_STATE(84)] = 1928,
  [SMALL_STATE(85)] = 1941,
  [SMALL_STATE(86)] = 1954,
  [SMALL_STATE(87)] = 1965,
  [SMALL_STATE(88)] = 1978,
  [SMALL_STATE(89)] = 1991,
  [SMALL_STATE(90)] = 2004,
  [SMALL_STATE(91)] = 2017,
  [SMALL_STATE(92)] = 2026,
  [SMALL_STATE(93)] = 2035,
  [SMALL_STATE(94)] = 2048,
  [SMALL_STATE(95)] = 2058,
  [SMALL_STATE(96)] = 2066,
  [SMALL_STATE(97)] = 2074,
  [SMALL_STATE(98)] = 2084,
  [SMALL_STATE(99)] = 2092,
  [SMALL_STATE(100)] = 2102,
  [SMALL_STATE(101)] = 2112,
  [SMALL_STATE(102)] = 2120,
  [SMALL_STATE(103)] = 2130,
  [SMALL_STATE(104)] = 2137,
  [SMALL_STATE(105)] = 2144,
  [SMALL_STATE(106)] = 2151,
  [SMALL_STATE(107)] = 2158,
  [SMALL_STATE(108)] = 2165,
  [SMALL_STATE(109)] = 2172,
  [SMALL_STATE(110)] = 2179,
  [SMALL_STATE(111)] = 2186,
  [SMALL_STATE(112)] = 2193,
  [SMALL_STATE(113)] = 2200,
  [SMALL_STATE(114)] = 2207,
  [SMALL_STATE(115)] = 2214,
  [SMALL_STATE(116)] = 2221,
  [SMALL_STATE(117)] = 2228,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nullary_ctor_pattern, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctor_pattern, 2),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(25),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(33),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(18),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(47),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(39),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(38),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(70),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(68),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_app_type, 2, .production_id = 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_pattern, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_pattern, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 5),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 5),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 3),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nullary_ctor_pattern, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 7),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 7),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 4),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 4),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 5),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 5),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 6),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 6),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_pattern, 1),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_pattern, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_params_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_params_repeat1, 2), SHIFT_REPEAT(49),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_params, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctor, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 4),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atomic_type, 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atomic_type, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 6),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_except_var, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_or_app, 3, .production_id = 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 5, .production_id = 4),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_or_app, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 7),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_name, 1),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 5),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_type, 1),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_type, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(106),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2), SHIFT_REPEAT(104),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2), SHIFT_REPEAT(9),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_pattern_repeat1, 2),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_pattern_repeat1, 2), SHIFT_REPEAT(29),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_type, 3),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_case_repeat1, 2),
  [306] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_case_repeat1, 2), SHIFT_REPEAT(27),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 3, .production_id = 5),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_bind, 3),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 6, .production_id = 2),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern_rest, 2),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [339] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
