#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 146
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 10

enum {
  sym_comment = 1,
  anon_sym_COLON = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_type = 8,
  anon_sym_COMMA = 9,
  sym_int = 10,
  sym_string = 11,
  sym_char = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  anon_sym_case = 15,
  anon_sym_DOT_DOT = 16,
  anon_sym_let = 17,
  anon_sym_EQ = 18,
  sym_l_ident = 19,
  sym_u_ident = 20,
  sym_source_file = 21,
  sym__decl = 22,
  sym_func_decl = 23,
  sym__type = 24,
  sym__atomic_type = 25,
  sym_type_name = 26,
  sym_var_type = 27,
  sym_app_type = 28,
  sym_func_type = 29,
  sym__expr = 30,
  sym_type_decl = 31,
  sym_type_decl_params = 32,
  sym_type_decl_ctor = 33,
  sym_type_decl_ctor_params = 34,
  sym__expr_except_var = 35,
  sym_ctor = 36,
  sym_tuple = 37,
  sym_list = 38,
  sym_case = 39,
  sym_branch = 40,
  sym__pattern = 41,
  sym__atomic_pattern = 42,
  sym_int_pattern = 43,
  sym_var_pattern = 44,
  sym_nullary_ctor_pattern = 45,
  sym_ctor_pattern = 46,
  sym_list_pattern = 47,
  sym_list_pattern_rest = 48,
  sym_tuple_pattern = 49,
  sym_func_or_app = 50,
  sym_func_params = 51,
  sym_let = 52,
  sym_let_bind = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_app_type_repeat1 = 55,
  aux_sym_type_decl_repeat1 = 56,
  aux_sym_type_decl_params_repeat1 = 57,
  aux_sym_tuple_repeat1 = 58,
  aux_sym_case_repeat1 = 59,
  aux_sym_ctor_pattern_repeat1 = 60,
  aux_sym_list_pattern_repeat1 = 61,
  aux_sym_let_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_type] = "type",
  [anon_sym_COMMA] = ",",
  [sym_int] = "int",
  [sym_string] = "string",
  [sym_char] = "char",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_case] = "case",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [sym_l_ident] = "l_ident",
  [sym_u_ident] = "u_ident",
  [sym_source_file] = "source_file",
  [sym__decl] = "_decl",
  [sym_func_decl] = "func_decl",
  [sym__type] = "_type",
  [sym__atomic_type] = "_atomic_type",
  [sym_type_name] = "type_name",
  [sym_var_type] = "var_type",
  [sym_app_type] = "app_type",
  [sym_func_type] = "func_type",
  [sym__expr] = "_expr",
  [sym_type_decl] = "type_decl",
  [sym_type_decl_params] = "type_decl_params",
  [sym_type_decl_ctor] = "type_decl_ctor",
  [sym_type_decl_ctor_params] = "type_decl_ctor_params",
  [sym__expr_except_var] = "_expr_except_var",
  [sym_ctor] = "ctor",
  [sym_tuple] = "tuple",
  [sym_list] = "list",
  [sym_case] = "case",
  [sym_branch] = "branch",
  [sym__pattern] = "_pattern",
  [sym__atomic_pattern] = "_atomic_pattern",
  [sym_int_pattern] = "int_pattern",
  [sym_var_pattern] = "var_pattern",
  [sym_nullary_ctor_pattern] = "nullary_ctor_pattern",
  [sym_ctor_pattern] = "ctor_pattern",
  [sym_list_pattern] = "list_pattern",
  [sym_list_pattern_rest] = "list_pattern_rest",
  [sym_tuple_pattern] = "tuple_pattern",
  [sym_func_or_app] = "func_or_app",
  [sym_func_params] = "func_params",
  [sym_let] = "let",
  [sym_let_bind] = "let_bind",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_app_type_repeat1] = "app_type_repeat1",
  [aux_sym_type_decl_repeat1] = "type_decl_repeat1",
  [aux_sym_type_decl_params_repeat1] = "type_decl_params_repeat1",
  [aux_sym_tuple_repeat1] = "tuple_repeat1",
  [aux_sym_case_repeat1] = "case_repeat1",
  [aux_sym_ctor_pattern_repeat1] = "ctor_pattern_repeat1",
  [aux_sym_list_pattern_repeat1] = "list_pattern_repeat1",
  [aux_sym_let_repeat1] = "let_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_int] = sym_int,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_l_ident] = sym_l_ident,
  [sym_u_ident] = sym_u_ident,
  [sym_source_file] = sym_source_file,
  [sym__decl] = sym__decl,
  [sym_func_decl] = sym_func_decl,
  [sym__type] = sym__type,
  [sym__atomic_type] = sym__atomic_type,
  [sym_type_name] = sym_type_name,
  [sym_var_type] = sym_var_type,
  [sym_app_type] = sym_app_type,
  [sym_func_type] = sym_func_type,
  [sym__expr] = sym__expr,
  [sym_type_decl] = sym_type_decl,
  [sym_type_decl_params] = sym_type_decl_params,
  [sym_type_decl_ctor] = sym_type_decl_ctor,
  [sym_type_decl_ctor_params] = sym_type_decl_ctor_params,
  [sym__expr_except_var] = sym__expr_except_var,
  [sym_ctor] = sym_ctor,
  [sym_tuple] = sym_tuple,
  [sym_list] = sym_list,
  [sym_case] = sym_case,
  [sym_branch] = sym_branch,
  [sym__pattern] = sym__pattern,
  [sym__atomic_pattern] = sym__atomic_pattern,
  [sym_int_pattern] = sym_int_pattern,
  [sym_var_pattern] = sym_var_pattern,
  [sym_nullary_ctor_pattern] = sym_nullary_ctor_pattern,
  [sym_ctor_pattern] = sym_ctor_pattern,
  [sym_list_pattern] = sym_list_pattern,
  [sym_list_pattern_rest] = sym_list_pattern_rest,
  [sym_tuple_pattern] = sym_tuple_pattern,
  [sym_func_or_app] = sym_func_or_app,
  [sym_func_params] = sym_func_params,
  [sym_let] = sym_let,
  [sym_let_bind] = sym_let_bind,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_app_type_repeat1] = aux_sym_app_type_repeat1,
  [aux_sym_type_decl_repeat1] = aux_sym_type_decl_repeat1,
  [aux_sym_type_decl_params_repeat1] = aux_sym_type_decl_params_repeat1,
  [aux_sym_tuple_repeat1] = aux_sym_tuple_repeat1,
  [aux_sym_case_repeat1] = aux_sym_case_repeat1,
  [aux_sym_ctor_pattern_repeat1] = aux_sym_ctor_pattern_repeat1,
  [aux_sym_list_pattern_repeat1] = aux_sym_list_pattern_repeat1,
  [aux_sym_let_repeat1] = aux_sym_let_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_l_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_u_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__decl] = {
    .visible = false,
    .named = true,
  },
  [sym_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym__atomic_type] = {
    .visible = false,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_var_type] = {
    .visible = true,
    .named = true,
  },
  [sym_app_type] = {
    .visible = true,
    .named = true,
  },
  [sym_func_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_type_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_decl_params] = {
    .visible = true,
    .named = true,
  },
  [sym_type_decl_ctor] = {
    .visible = true,
    .named = true,
  },
  [sym_type_decl_ctor_params] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_except_var] = {
    .visible = false,
    .named = true,
  },
  [sym_ctor] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_case] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym__atomic_pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_int_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_var_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_nullary_ctor_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_ctor_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_list_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_list_pattern_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_func_or_app] = {
    .visible = true,
    .named = true,
  },
  [sym_func_params] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_let_bind] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_app_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_decl_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_case_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ctor_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_let_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_head = 2,
  field_name = 3,
  field_params = 4,
  field_pattern = 5,
  field_rhs = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_head] = "head",
  [field_name] = "name",
  [field_params] = "params",
  [field_pattern] = "pattern",
  [field_rhs] = "rhs",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_head, 0},
  [3] =
    {field_name, 0},
    {field_params, 1},
  [5] =
    {field_name, 1},
    {field_params, 2},
  [7] =
    {field_body, 4},
    {field_name, 0},
    {field_type, 2},
  [10] =
    {field_body, 2},
  [11] =
    {field_body, 3},
  [12] =
    {field_pattern, 0},
    {field_rhs, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 51,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 58,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(13);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == 'c') ADVANCE(34);
      if (lookahead == 'l') ADVANCE(35);
      if (lookahead == 't') ADVANCE(41);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(13);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == 'c') ADVANCE(34);
      if (lookahead == 'l') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(43);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(43);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(2);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(5);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == 't') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_case);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'p') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 's') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 't') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_l_ident);
      if (lookahead == 'y') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_l_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_u_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 14},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 8},
  [82] = {.lex_state = 14},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 14},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 8},
  [92] = {.lex_state = 14},
  [93] = {.lex_state = 8},
  [94] = {.lex_state = 8},
  [95] = {.lex_state = 8},
  [96] = {.lex_state = 14},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 14},
  [100] = {.lex_state = 8},
  [101] = {.lex_state = 14},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 14},
  [105] = {.lex_state = 6},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 14},
  [115] = {.lex_state = 14},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 6},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 8},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 6},
  [134] = {.lex_state = 8},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_l_ident] = ACTIONS(1),
    [sym_u_ident] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(132),
    [sym__decl] = STATE(57),
    [sym_func_decl] = STATE(57),
    [sym_type_decl] = STATE(57),
    [aux_sym_source_file_repeat1] = STATE(57),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(7),
    [sym_l_ident] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_RPAREN,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(17), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(109), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [49] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(29), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(107), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [95] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(35), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(83), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [141] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(35), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(83), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [187] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(35), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(83), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [233] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(35), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(83), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [279] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_u_ident,
    ACTIONS(45), 1,
      sym_l_ident,
    STATE(78), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(85), 1,
      sym_func_params,
    ACTIONS(43), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(72), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [322] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(47), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(138), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [365] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(49), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(124), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [408] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(35), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(83), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [451] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(43), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(72), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [494] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(51), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(136), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [537] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      sym_u_ident,
    ACTIONS(45), 1,
      sym_l_ident,
    STATE(78), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(85), 1,
      sym_func_params,
    ACTIONS(53), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(122), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [580] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_case,
    ACTIONS(23), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      sym_l_ident,
    ACTIONS(27), 1,
      sym_u_ident,
    STATE(51), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(58), 1,
      sym_func_params,
    ACTIONS(55), 3,
      sym_int,
      sym_string,
      sym_char,
    STATE(139), 8,
      sym__expr,
      sym__expr_except_var,
      sym_ctor,
      sym_tuple,
      sym_list,
      sym_case,
      sym_func_or_app,
      sym_let,
  [623] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_COMMA,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    ACTIONS(67), 1,
      anon_sym_DOT_DOT,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    STATE(129), 1,
      sym_list_pattern_rest,
    STATE(106), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [664] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DOT_DOT,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
    STATE(137), 1,
      sym_list_pattern_rest,
    STATE(106), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [705] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_DOT_DOT,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    ACTIONS(79), 1,
      anon_sym_RBRACK,
    STATE(130), 1,
      sym_list_pattern_rest,
    STATE(102), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [746] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(83), 1,
      sym_u_ident,
    ACTIONS(81), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(20), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [780] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(83), 1,
      sym_u_ident,
    ACTIONS(85), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [814] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(92), 1,
      sym_int,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(98), 1,
      sym_l_ident,
    ACTIONS(101), 1,
      sym_u_ident,
    ACTIONS(90), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
      aux_sym_ctor_pattern_repeat1,
  [848] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(90), 1,
      sym_branch,
    STATE(143), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [883] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(121), 1,
      sym_branch,
    STATE(143), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [918] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(121), 1,
      sym_branch,
    STATE(143), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [953] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(106), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [985] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(98), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1017] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    STATE(106), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1049] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    STATE(121), 1,
      sym_branch,
    STATE(143), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1081] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_int,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      sym_l_ident,
    ACTIONS(71), 1,
      sym_u_ident,
    STATE(106), 8,
      sym__pattern,
      sym__atomic_pattern,
      sym_int_pattern,
      sym_var_pattern,
      sym_nullary_ctor_pattern,
      sym_ctor_pattern,
      sym_list_pattern,
      sym_tuple_pattern,
  [1110] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      sym_l_ident,
    ACTIONS(124), 1,
      sym_u_ident,
    STATE(30), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
    ACTIONS(116), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
  [1136] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_l_ident,
    ACTIONS(133), 1,
      sym_u_ident,
    ACTIONS(127), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(33), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1160] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_l_ident,
    ACTIONS(133), 1,
      sym_u_ident,
    STATE(127), 1,
      sym_type_decl_ctor_params,
    ACTIONS(135), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    STATE(38), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1186] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_l_ident,
    ACTIONS(133), 1,
      sym_u_ident,
    ACTIONS(137), 3,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
    STATE(30), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_u_ident,
    ACTIONS(139), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_u_ident,
    ACTIONS(143), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_u_ident,
    ACTIONS(147), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1261] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_l_ident,
    ACTIONS(133), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(110), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1284] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_l_ident,
    ACTIONS(133), 1,
      sym_u_ident,
    ACTIONS(151), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    STATE(30), 4,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
      aux_sym_app_type_repeat1,
  [1307] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_u_ident,
    ACTIONS(153), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1324] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_u_ident,
    ACTIONS(157), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1341] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_u_ident,
    ACTIONS(161), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1358] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_l_ident,
    ACTIONS(133), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(123), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1381] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_l_ident,
    ACTIONS(133), 1,
      sym_u_ident,
    STATE(31), 3,
      sym__atomic_type,
      sym_type_name,
      sym_var_type,
    STATE(125), 3,
      sym__type,
      sym_app_type,
      sym_func_type,
  [1404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_u_ident,
    ACTIONS(81), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1421] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_u_ident,
    ACTIONS(167), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1438] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_u_ident,
    ACTIONS(171), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_u_ident,
    ACTIONS(175), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1472] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_u_ident,
    ACTIONS(179), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1489] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_u_ident,
    ACTIONS(183), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1506] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_u_ident,
    ACTIONS(187), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_l_ident,
  [1523] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_l_ident,
    STATE(52), 1,
      aux_sym_type_decl_params_repeat1,
    ACTIONS(191), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1541] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_l_ident,
    STATE(52), 1,
      aux_sym_type_decl_params_repeat1,
    ACTIONS(195), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      sym_u_ident,
    ACTIONS(200), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_l_ident,
  [1575] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_u_ident,
    ACTIONS(204), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_l_ident,
  [1591] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_u_ident,
    ACTIONS(208), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      sym_l_ident,
  [1607] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    ACTIONS(214), 1,
      anon_sym_type,
    ACTIONS(217), 1,
      sym_l_ident,
    STATE(56), 4,
      sym__decl,
      sym_func_decl,
      sym_type_decl,
      aux_sym_source_file_repeat1,
  [1626] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(9), 1,
      sym_l_ident,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
    STATE(56), 4,
      sym__decl,
      sym_func_decl,
      sym_type_decl,
      aux_sym_source_file_repeat1,
  [1645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_DASH_GT,
    ACTIONS(222), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1659] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1707] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1719] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1743] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1767] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1779] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1791] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1803] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1839] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_l_ident,
  [1851] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LBRACE,
    ACTIONS(260), 1,
      sym_l_ident,
    STATE(75), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1865] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
    ACTIONS(263), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1879] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_LBRACE,
    ACTIONS(270), 1,
      sym_l_ident,
    STATE(87), 1,
      aux_sym_type_decl_params_repeat1,
    STATE(145), 1,
      sym_type_decl_params,
  [1895] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(52), 1,
      aux_sym_type_decl_params_repeat1,
    ACTIONS(191), 3,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      sym_l_ident,
  [1907] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    ACTIONS(274), 1,
      sym_l_ident,
    STATE(75), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [1921] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_list_pattern_repeat1,
    ACTIONS(276), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1935] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
    ACTIONS(283), 1,
      sym_u_ident,
    STATE(120), 1,
      sym_type_decl_ctor,
  [1948] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      ts_builtin_sym_end,
    ACTIONS(287), 2,
      anon_sym_type,
      sym_l_ident,
  [1959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1968] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      ts_builtin_sym_end,
    ACTIONS(291), 2,
      anon_sym_type,
      sym_l_ident,
  [1979] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_DASH_GT,
    ACTIONS(222), 2,
      anon_sym_LBRACE,
      sym_l_ident,
  [1990] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
  [2003] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_l_ident,
    ACTIONS(297), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      aux_sym_type_decl_params_repeat1,
  [2016] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_tuple_repeat1,
  [2029] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      aux_sym_type_decl_repeat1,
  [2042] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    STATE(108), 1,
      aux_sym_case_repeat1,
  [2055] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_u_ident,
    ACTIONS(309), 1,
      anon_sym_RBRACE,
    STATE(103), 1,
      sym_type_decl_ctor,
  [2068] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      ts_builtin_sym_end,
    ACTIONS(313), 2,
      anon_sym_type,
      sym_l_ident,
  [2079] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_u_ident,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
    STATE(120), 1,
      sym_type_decl_ctor,
  [2092] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_u_ident,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
    STATE(120), 1,
      sym_type_decl_ctor,
  [2105] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_u_ident,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      sym_type_decl_ctor,
  [2118] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      ts_builtin_sym_end,
    ACTIONS(323), 2,
      anon_sym_type,
      sym_l_ident,
  [2129] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    STATE(116), 1,
      aux_sym_type_decl_repeat1,
  [2142] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    STATE(113), 1,
      aux_sym_list_pattern_repeat1,
  [2155] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      ts_builtin_sym_end,
    ACTIONS(333), 2,
      anon_sym_type,
      sym_l_ident,
  [2166] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_u_ident,
    ACTIONS(335), 1,
      anon_sym_RBRACE,
    STATE(120), 1,
      sym_type_decl_ctor,
  [2179] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      ts_builtin_sym_end,
    ACTIONS(339), 2,
      anon_sym_type,
      sym_l_ident,
  [2190] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_COMMA,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
    STATE(117), 1,
      aux_sym_list_pattern_repeat1,
  [2203] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_RBRACE,
    ACTIONS(347), 1,
      anon_sym_COMMA,
    STATE(111), 1,
      aux_sym_type_decl_repeat1,
  [2216] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      ts_builtin_sym_end,
    ACTIONS(351), 2,
      anon_sym_type,
      sym_l_ident,
  [2227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_l_ident,
    STATE(79), 2,
      sym_let_bind,
      aux_sym_let_repeat1,
  [2238] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2247] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_COMMA,
    ACTIONS(355), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym_tuple_repeat1,
  [2260] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(357), 1,
      anon_sym_COMMA,
    STATE(112), 1,
      aux_sym_case_repeat1,
  [2273] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_RPAREN,
    ACTIONS(361), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_tuple_repeat1,
  [2286] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_DASH_GT,
    ACTIONS(363), 2,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
  [2297] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
    ACTIONS(367), 1,
      anon_sym_COMMA,
    STATE(116), 1,
      aux_sym_type_decl_repeat1,
  [2310] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_RBRACE,
    ACTIONS(371), 1,
      anon_sym_COMMA,
    STATE(112), 1,
      aux_sym_case_repeat1,
  [2323] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    ACTIONS(374), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_list_pattern_repeat1,
  [2336] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      ts_builtin_sym_end,
    ACTIONS(378), 2,
      anon_sym_type,
      sym_l_ident,
  [2347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      ts_builtin_sym_end,
    ACTIONS(382), 2,
      anon_sym_type,
      sym_l_ident,
  [2358] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      anon_sym_RBRACE,
    ACTIONS(386), 1,
      anon_sym_COMMA,
    STATE(116), 1,
      aux_sym_type_decl_repeat1,
  [2371] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    ACTIONS(389), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_list_pattern_repeat1,
  [2384] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DOT_DOT,
    STATE(137), 1,
      sym_list_pattern_rest,
  [2394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DOT_DOT,
    STATE(142), 1,
      sym_list_pattern_rest,
  [2404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 2,
      anon_sym_LBRACE,
      sym_l_ident,
  [2428] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_DASH_GT,
    ACTIONS(393), 1,
      anon_sym_RPAREN,
  [2438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2446] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_DASH_GT,
    ACTIONS(397), 1,
      anon_sym_LBRACE,
  [2456] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DOT_DOT,
    STATE(141), 1,
      sym_list_pattern_rest,
  [2466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_u_ident,
    STATE(120), 1,
      sym_type_decl_ctor,
  [2484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
  [2491] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
  [2498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      anon_sym_RBRACK,
  [2505] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      ts_builtin_sym_end,
  [2512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      sym_l_ident,
  [2519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      sym_u_ident,
  [2526] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      anon_sym_EQ,
  [2533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      anon_sym_RBRACE,
  [2540] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      anon_sym_RBRACK,
  [2547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      anon_sym_LBRACE,
  [2554] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(417), 1,
      anon_sym_RBRACE,
  [2561] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(419), 1,
      anon_sym_RPAREN,
  [2568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(421), 1,
      anon_sym_RBRACK,
  [2575] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
  [2582] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(423), 1,
      anon_sym_DASH_GT,
  [2589] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(425), 1,
      anon_sym_COLON,
  [2596] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(427), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 95,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 187,
  [SMALL_STATE(7)] = 233,
  [SMALL_STATE(8)] = 279,
  [SMALL_STATE(9)] = 322,
  [SMALL_STATE(10)] = 365,
  [SMALL_STATE(11)] = 408,
  [SMALL_STATE(12)] = 451,
  [SMALL_STATE(13)] = 494,
  [SMALL_STATE(14)] = 537,
  [SMALL_STATE(15)] = 580,
  [SMALL_STATE(16)] = 623,
  [SMALL_STATE(17)] = 664,
  [SMALL_STATE(18)] = 705,
  [SMALL_STATE(19)] = 746,
  [SMALL_STATE(20)] = 780,
  [SMALL_STATE(21)] = 814,
  [SMALL_STATE(22)] = 848,
  [SMALL_STATE(23)] = 883,
  [SMALL_STATE(24)] = 918,
  [SMALL_STATE(25)] = 953,
  [SMALL_STATE(26)] = 985,
  [SMALL_STATE(27)] = 1017,
  [SMALL_STATE(28)] = 1049,
  [SMALL_STATE(29)] = 1081,
  [SMALL_STATE(30)] = 1110,
  [SMALL_STATE(31)] = 1136,
  [SMALL_STATE(32)] = 1160,
  [SMALL_STATE(33)] = 1186,
  [SMALL_STATE(34)] = 1210,
  [SMALL_STATE(35)] = 1227,
  [SMALL_STATE(36)] = 1244,
  [SMALL_STATE(37)] = 1261,
  [SMALL_STATE(38)] = 1284,
  [SMALL_STATE(39)] = 1307,
  [SMALL_STATE(40)] = 1324,
  [SMALL_STATE(41)] = 1341,
  [SMALL_STATE(42)] = 1358,
  [SMALL_STATE(43)] = 1381,
  [SMALL_STATE(44)] = 1404,
  [SMALL_STATE(45)] = 1421,
  [SMALL_STATE(46)] = 1438,
  [SMALL_STATE(47)] = 1455,
  [SMALL_STATE(48)] = 1472,
  [SMALL_STATE(49)] = 1489,
  [SMALL_STATE(50)] = 1506,
  [SMALL_STATE(51)] = 1523,
  [SMALL_STATE(52)] = 1541,
  [SMALL_STATE(53)] = 1559,
  [SMALL_STATE(54)] = 1575,
  [SMALL_STATE(55)] = 1591,
  [SMALL_STATE(56)] = 1607,
  [SMALL_STATE(57)] = 1626,
  [SMALL_STATE(58)] = 1645,
  [SMALL_STATE(59)] = 1659,
  [SMALL_STATE(60)] = 1671,
  [SMALL_STATE(61)] = 1683,
  [SMALL_STATE(62)] = 1695,
  [SMALL_STATE(63)] = 1707,
  [SMALL_STATE(64)] = 1719,
  [SMALL_STATE(65)] = 1731,
  [SMALL_STATE(66)] = 1743,
  [SMALL_STATE(67)] = 1755,
  [SMALL_STATE(68)] = 1767,
  [SMALL_STATE(69)] = 1779,
  [SMALL_STATE(70)] = 1791,
  [SMALL_STATE(71)] = 1803,
  [SMALL_STATE(72)] = 1815,
  [SMALL_STATE(73)] = 1827,
  [SMALL_STATE(74)] = 1839,
  [SMALL_STATE(75)] = 1851,
  [SMALL_STATE(76)] = 1865,
  [SMALL_STATE(77)] = 1879,
  [SMALL_STATE(78)] = 1895,
  [SMALL_STATE(79)] = 1907,
  [SMALL_STATE(80)] = 1921,
  [SMALL_STATE(81)] = 1935,
  [SMALL_STATE(82)] = 1948,
  [SMALL_STATE(83)] = 1959,
  [SMALL_STATE(84)] = 1968,
  [SMALL_STATE(85)] = 1979,
  [SMALL_STATE(86)] = 1990,
  [SMALL_STATE(87)] = 2003,
  [SMALL_STATE(88)] = 2016,
  [SMALL_STATE(89)] = 2029,
  [SMALL_STATE(90)] = 2042,
  [SMALL_STATE(91)] = 2055,
  [SMALL_STATE(92)] = 2068,
  [SMALL_STATE(93)] = 2079,
  [SMALL_STATE(94)] = 2092,
  [SMALL_STATE(95)] = 2105,
  [SMALL_STATE(96)] = 2118,
  [SMALL_STATE(97)] = 2129,
  [SMALL_STATE(98)] = 2142,
  [SMALL_STATE(99)] = 2155,
  [SMALL_STATE(100)] = 2166,
  [SMALL_STATE(101)] = 2179,
  [SMALL_STATE(102)] = 2190,
  [SMALL_STATE(103)] = 2203,
  [SMALL_STATE(104)] = 2216,
  [SMALL_STATE(105)] = 2227,
  [SMALL_STATE(106)] = 2238,
  [SMALL_STATE(107)] = 2247,
  [SMALL_STATE(108)] = 2260,
  [SMALL_STATE(109)] = 2273,
  [SMALL_STATE(110)] = 2286,
  [SMALL_STATE(111)] = 2297,
  [SMALL_STATE(112)] = 2310,
  [SMALL_STATE(113)] = 2323,
  [SMALL_STATE(114)] = 2336,
  [SMALL_STATE(115)] = 2347,
  [SMALL_STATE(116)] = 2358,
  [SMALL_STATE(117)] = 2371,
  [SMALL_STATE(118)] = 2384,
  [SMALL_STATE(119)] = 2394,
  [SMALL_STATE(120)] = 2404,
  [SMALL_STATE(121)] = 2412,
  [SMALL_STATE(122)] = 2420,
  [SMALL_STATE(123)] = 2428,
  [SMALL_STATE(124)] = 2438,
  [SMALL_STATE(125)] = 2446,
  [SMALL_STATE(126)] = 2456,
  [SMALL_STATE(127)] = 2466,
  [SMALL_STATE(128)] = 2474,
  [SMALL_STATE(129)] = 2484,
  [SMALL_STATE(130)] = 2491,
  [SMALL_STATE(131)] = 2498,
  [SMALL_STATE(132)] = 2505,
  [SMALL_STATE(133)] = 2512,
  [SMALL_STATE(134)] = 2519,
  [SMALL_STATE(135)] = 2526,
  [SMALL_STATE(136)] = 2533,
  [SMALL_STATE(137)] = 2540,
  [SMALL_STATE(138)] = 2547,
  [SMALL_STATE(139)] = 2554,
  [SMALL_STATE(140)] = 2561,
  [SMALL_STATE(141)] = 2568,
  [SMALL_STATE(142)] = 2575,
  [SMALL_STATE(143)] = 2582,
  [SMALL_STATE(144)] = 2589,
  [SMALL_STATE(145)] = 2596,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(144),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nullary_ctor_pattern, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctor_pattern, 2),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(26),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(35),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(18),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(50),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ctor_pattern_repeat1, 2), SHIFT_REPEAT(44),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(42),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(55),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_app_type_repeat1, 2), SHIFT_REPEAT(53),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl_ctor, 1, .production_id = 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_app_type, 2, .production_id = 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_pattern, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_pattern, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 5),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 5),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl_ctor_params, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 5),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 5),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 6),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 6),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 4),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 4),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nullary_ctor_pattern, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 4),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern, 7),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_pattern, 7),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 2),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple_pattern, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_pattern, 1),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_pattern, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_params, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_decl_params_repeat1, 2),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_decl_params_repeat1, 2), SHIFT_REPEAT(52),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_name, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atomic_type, 3),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atomic_type, 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_type, 1),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_type, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [214] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(134),
  [217] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(144),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_or_app, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_except_var, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 7),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ctor, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 5, .production_id = 8),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 5),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_or_app, 3, .production_id = 7),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 4),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 6),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_repeat1, 2), SHIFT_REPEAT(135),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_repeat1, 2), SHIFT_REPEAT(11),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_pattern_repeat1, 2),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_pattern_repeat1, 2), SHIFT_REPEAT(29),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 7, .production_id = 1),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 7, .production_id = 1),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 4, .production_id = 1),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 4, .production_id = 1),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl_params, 1),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 5, .production_id = 1),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 5, .production_id = 1),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 7, .production_id = 5),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 7, .production_id = 5),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 5, .production_id = 5),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 5, .production_id = 5),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 8, .production_id = 5),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 8, .production_id = 5),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 6, .production_id = 6),
  [351] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_decl, 6, .production_id = 6),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_type, 3),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_case_repeat1, 2),
  [371] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_case_repeat1, 2), SHIFT_REPEAT(28),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 6, .production_id = 1),
  [378] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 6, .production_id = 1),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 6, .production_id = 5),
  [382] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_decl, 6, .production_id = 5),
  [384] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_decl_repeat1, 2),
  [386] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_decl_repeat1, 2), SHIFT_REPEAT(128),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_bind, 3),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 3, .production_id = 9),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl_ctor, 2, .production_id = 4),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_pattern_rest, 2),
  [403] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
